### ISSUE TITLE
this not working

### ISSUE THREAD

**Issue by danishaali9** [Moenus/wp-gitlab-updater#14] opened 2021-01-26 12:16 UTC
I am trying to update a plugin but i couldn't understand when you said ', put it into your plugin and call it:' what do you mean by this? i am a beginner in WP i don't know maybe i am wrong in some implementation but i am listing what i have tried.

i have a private repo which is apparently a WP plugin. i 

i made a private gitlab repo
i pushed  an apparently called WP plugin in that repo ( after 1. adding 'src/plugin-updater.php' and 'src/updater-base.php' from my local WP and 2. adding that repo access token, gitlab url and repo).
now as i already said. i don't know about 'put it into your plugin and call it'. so maybe thats the problem. otherwise what i think work now is, whenever i make a change in any file in gitlab repo. it should show me a message about updating that plugin on local. is this what it is ought to do? right?

**Comment by florianbrinkmann** [comment] 2021-01-27 07:32
> I am trying to update a plugin but i couldn't understand when you said ', put it into your plugin and call it:' what do you mean by this?

I mean that you need to copy the files into your plugin folder and run the following code in the readme file to call the updater.

> otherwise what i think work now is, whenever i make a change in any file in gitlab repo. it should show me a message about updating that plugin on local. is this what it is ought to do? right?

No. The updater uses tags to check if a new version is available. So after inserting the updater code in your plugin and using the correct credentials for your private repo, you need to create a tag in GitLab with a version number that is higher than the current plugin version. Then you sould see a update notification.

**Comment by danishaali9** [comment] 2021-01-27 07:47
I mean that you need to copy the files into your plugin folder ( i did that already )

run the following code in the readme file to call the updater.

![image](https://user-images.githubusercontent.com/35070443/105959171-6248c400-609d-11eb-8e51-6bcc3df46083.png)

you mean this code ?  that's what i wanted to ask. that where i have to paste the code to run it. in index.php of my plugin or in any of your files?

**Comment by florianbrinkmann** [comment] 2021-01-27 08:28
> you mean this code ? 

Yes. That code goes into your `index.php`.

**Comment by danishaali9** [comment] 2021-01-27 09:25
can you please guide me that where should i put that code in? because i am getting errors,  in main class of index.php? .i.e. 
![image](https://user-images.githubusercontent.com/35070443/105970460-39c7c680-60ab-11eb-983d-ada187383d3a.png) 
it is not getting namespace. and please verify what should i put in place of 
		'slug' => 'SlugOfPlugin', 
		'plugin_base_name' => 'BaseNameOfThePlugin',

**Comment by florianbrinkmann** [comment] 2021-01-27 09:48
Which error do you get when you run the code?

`slug` is the directory name of the plugin, `basename` is the slug + the main file, so in your case: `nameOfPluginFolder/index.php`.

**Comment by danishaali9** [comment] 2021-01-27 09:50
![image](https://user-images.githubusercontent.com/35070443/105973812-ff602880-60ae-11eb-92ed-de9accd5b9ca.png)

**Comment by florianbrinkmann** [comment] 2021-01-27 10:30
If the site also uses the WP plugin of GitLab updater, you need to check if the class already exists before including the updater file in your plugin. Because otherwise, the Class is loaded twice and that is the error.

**Comment by arslbbt** [comment] 2021-02-02 09:51
@florianbrinkmann I followed the same step as above mentioned but my plugin didn't show an update option.

**Comment by florianbrinkmann** [comment] 2021-02-02 10:34
@arslbbt what steps exactly did you follow to use the updater script?

**Comment by arslbbt** [comment] 2021-02-02 10:39
@florianbrinkmann here is my custom plugin repository please let me know what is an issue.
![image](https://user-images.githubusercontent.com/12788132/106588452-9d9b3500-656c-11eb-84f0-d5cf71f488d8.png)
![image](https://user-images.githubusercontent.com/12788132/106588573-c58a9880-656c-11eb-893f-05b4667a4496.png)

**Comment by arslbbt** [comment] 2021-02-02 10:41
@florianbrinkmann is there any issue to configure it please let me know?

**Comment by florianbrinkmann** [comment] 2021-02-02 10:42
I think it is not a good idea to post things like access tokens publicly, @arslbbt.

What I can say from the screenshots, the basename of the plugin needs to be something like `plugin-test/index.php`. And when the connection details are correct, you need to create a Git tag with a version number greater than 2.6.

**Comment by arslbbt** [comment] 2021-02-02 10:42
my respository
![image](https://user-images.githubusercontent.com/12788132/106588994-46e22b00-656d-11eb-9b40-70eb85cd30a0.png)

**Comment by arslbbt** [comment] 2021-02-02 10:45
> I think it is not a good idea to post things like access tokens publicly, @arslbbt.
> 
> What I can say from the screenshots, the basename of the plugin needs to be something like `plugin-test/index.php`. And when the connection details are correct, you need to create a Git tag with a version number greater than 2.6.

@florianbrinkmann thanks for an access token. I have created many tags but didn't update it.

**Comment by florianbrinkmann** [comment] 2021-02-02 10:47
You’re welcome, you should remove the old access token and create a new one, because everyone can browse the history of the comment changes.

Have you set the correct scope for the access token? And is anything in the error log?

Edit: and have you updated the basename value?

**Comment by arslbbt** [comment] 2021-02-02 11:01
@florianbrinkmann I have created a new access token and added in my plugin and also added in Gitlab updater plugin and tags but didn't work.
can you please let me know what is a slug in GitLab?
Previously I added a scope for API and read_registry but right now I scope it all.
![image](https://user-images.githubusercontent.com/12788132/106591095-aa6d5800-656f-11eb-9a88-3504e64db42e.png)

**Comment by florianbrinkmann** [comment] 2021-02-02 11:08
The `slug` has nothing to do with GitLab, it is the directory name of your plugin. In the readme file is everything explained that you need to know to get it running, for example, that you need to include both the `plugin-updater.php` and `updater-base.php` (https://github.com/krafit/wp-gitlab-updater#readme). Please read the readme and follow the steps that are described there.

**Comment by arslbbt** [comment] 2021-02-02 11:15
@florianbrinkmann can you please check my above code, is there any issue?

**Comment by florianbrinkmann** [comment] 2021-02-02 11:25
Yes, you did not include the `updater-base.php`

**Comment by arslbbt** [comment] 2021-02-02 11:40
@florianbrinkmann still not work

**Comment by florianbrinkmann** [comment] 2021-02-02 12:21
I just installed the updater as a WP plugin and tried it with one of my projects, and it worked. Maybe you could try to use it as a WordPress plugin first, so via the settings screen under »Settings« › »GitLab Updater«. If that already does not work, something is wrong with the tags or access token.

**Comment by arslbbt** [comment] 2021-02-02 12:46
@florianbrinkmann I'm getting the update option but the issue is that if I updated the version in local then they compare with tag (version) and give me an option update otherwise didn't

**Comment by florianbrinkmann** [comment] 2021-02-02 12:54
Sorry, I cannot follow. You get the update notification, and what happens when you want to update the plugin?

**Comment by arslbbt** [comment] 2021-02-02 13:03
maintenance error

**Comment by florianbrinkmann** [comment] 2021-02-02 13:05
> maintenance error

What is a maintenance error?

**Comment by arslbbt** [comment] 2021-02-02 13:14
@florianbrinkmann 
![image](https://user-images.githubusercontent.com/12788132/106605188-6d5e9100-6582-11eb-8b0b-020d86b5bb0e.png)

**Comment by florianbrinkmann** [comment] 2021-02-02 13:15
Something in the error log?

**Comment by arslbbt** [comment] 2021-02-02 13:17
@florianbrinkmann I think the file path issue, how I resolve? 
![image](https://user-images.githubusercontent.com/12788132/106605564-dba35380-6582-11eb-8c1a-9112fd756177.png)

**Comment by florianbrinkmann** [comment] 2021-02-02 13:25
I don’t know if that is related to the update issue. Have you tried it on a webserver that is not on your local machine? Maybe it works there. As I cannot reproduce the issue but was able to use the updater, I will close it.

**Closed as completed by florianbrinkmann** 2021-02-02 13:25 UTC
